apiVersion: v1
kind: PersistentVolume
metadata:
  name: mylocal-3
  labels:
    volume-type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  hostPath:
    path: /home/ec2-user/cassandra-data-3
